/* Form definition file generated by fdesign on Fri Jan 16 14:58:39 2026 */

#include "ui.h"
#include "material.h"

/***************************************
 ***************************************/

FD_Materialverwaltung *
create_form_Materialverwaltung( void )
{
    FL_OBJECT *obj;
    FD_Materialverwaltung *fdui = ( FD_Materialverwaltung * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Materialverwaltung = fl_bgn_form( FL_NO_BOX, 1280, 720 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 1280, 720, "" );

    fdui->btn_help = obj = fl_add_button( FL_NORMAL_BUTTON, 100, 20, 30, 30, "?" );
    fl_set_object_callback( obj, cb_help, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->quit = obj = fl_add_button( FL_NORMAL_BUTTON, 1050, 670, 200, 30, "Speichern und Verlassen" );
    fl_set_object_callback( obj, cb_quit, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->btn_display = obj = fl_add_button( FL_NORMAL_BUTTON, 500, 20, 250, 30, "Gesamten Bestand anzeigen" );
    fl_set_object_callback( obj, cb_display, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->input_name = obj = fl_add_input( FL_NORMAL_INPUT, 350, 80, 200, 30, "Artikelbezeichnung" );
    fl_set_object_callback( obj, cb_name, 0 );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->input_nr = obj = fl_add_input( FL_NORMAL_INPUT, 700, 80, 100, 30, "Artikelnummer" );
    fl_set_object_callback( obj, cb_nr, 0 );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->input_count = obj = fl_add_input( FL_NORMAL_INPUT, 900, 80, 50, 30, "Bestand" );
    fl_set_object_callback( obj, cb_count, 0 );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->btn_search = obj = fl_add_button( FL_NORMAL_BUTTON, 300, 140, 200, 30, "Material suchen" );
    fl_set_object_callback( obj, cb_search, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->btn_in = obj = fl_add_button( FL_NORMAL_BUTTON, 550, 140, 200, 30, "Material hinzufuegen" );
    fl_set_object_callback( obj, cb_in, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->btn_out = obj = fl_add_button( FL_NORMAL_BUTTON, 800, 140, 200, 30, "Material entfernen" );
    fl_set_object_callback( obj, cb_out, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->btn_clear = obj = fl_add_button( FL_NORMAL_BUTTON, 1000, 80, 30, 30, "X" );
    fl_set_object_callback( obj, cb_clear, (long)fdui );
    fl_set_object_lstyle( obj, FL_FIXEDBOLD_STYLE );

    fdui->browser = obj = fl_add_browser( FL_HOLD_BROWSER, 100, 200, 1080, 450, "" );
    fl_set_object_callback( obj, cb_browser, (long)fdui );
    fl_set_browser_dblclick_callback( obj, cb_browser_dblclick, (long)fdui );
    fl_set_browser_fontstyle(obj, FL_FIXEDBOLD_STYLE);

    fl_end_form( );

    fdui->Materialverwaltung->fdui = fdui;

    return fdui;
}
