#ifndef FD_Materialverwaltung_h_
#define FD_Materialverwaltung_h_

/* Header file generated by fdesign on Fri Jan 16 14:58:39 2026 */
#include <forms.h>
#include "ringlist.h"


/* Callbacks, globals and object handlers */

void cb_quit( FL_OBJECT *, long );
void cb_nr( FL_OBJECT *, long );
void cb_name( FL_OBJECT *, long );
void cb_count( FL_OBJECT *, long );
void cb_search( FL_OBJECT *, long );
void cb_in( FL_OBJECT *, long );
void cb_browser( FL_OBJECT *, long );
void cb_browser_dblclick( FL_OBJECT *, long );
void cb_display( FL_OBJECT *, long );
void cb_out( FL_OBJECT *, long );
void cb_clear( FL_OBJECT *, long );
void cb_help( FL_OBJECT *, long );


/* Forms and Objects */

enum STATE{STATE_IDLE, STATE_HELP, STATE_DISPLAY, STATE_SEARCH, STATE_ADD, STATE_REMOVE};

typedef struct {
    FL_FORM   * Materialverwaltung;
    tList     * materials;
    void      * vdata;
    char      * cdata;
    long        ldata;
    char        state;
    char      * filepath;
    int         data_altered;
    FL_OBJECT * btn_display;
    FL_OBJECT * input_nr;
    FL_OBJECT * input_name;
    FL_OBJECT * input_count;
    FL_OBJECT * btn_search;
    FL_OBJECT * btn_in;
    FL_OBJECT * btn_out;
    FL_OBJECT * btn_clear;
    FL_OBJECT * btn_help;
    FL_OBJECT * browser;
    FL_OBJECT * quit;
} FD_Materialverwaltung;

extern FD_Materialverwaltung * create_form_Materialverwaltung( void );
extern FD_Materialverwaltung *fdui;

#endif /* FD_Materialverwaltung_h_ */
